name: 'bookstore-app'
services:
  catalog-service:
    image: kadiyalajai/bookstore-catalog-service
    container_name: catalog-service
    environment:
      - DB_URL=jdbc:postgresql://catalog-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8081:8081"
    depends_on:
      catalog-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m